# clara_app/constants.py

SUPPORTED_LANGUAGES = [
    ('arabic', 'Arabic'),
    ('bengali', 'Bengali'),
    ('bulgarian', 'Bulgarian'),
    ('cantonese', 'Cantonese'),
    ('chinese', 'Chinese'),
    ('croatian', 'Croatian'),
    ('czech', 'Czech'),
    ('danish', 'Danish'),
    ('dutch', 'Dutch'),
    ('english', 'English'),
    ('faroese', 'Faroese'),
    ('farsi', 'Farsi'),
    ('finnish', 'Finnish'),
    ('french', 'French'),
    ('german', 'German'),
    ('greek', 'Greek'),
    ('hebrew', 'Hebrew'),
    ('hindi', 'Hindi'),
    ('hungarian', 'Hungarian'),
    ('icelandic', 'Icelandic'),
    ('italian', 'Italian'),
    ('japanese', 'Japanese'),
    ('korean', 'Korean'),
    ('latin', 'Latin'),
    ('mandarin', 'Mandarin'),
    ('norwegian', 'Norwegian'),
    ('old norse', 'Old Norse'),
    ('polish', 'Polish'),
    ('portuguese', 'Portuguese'),
    ('romanian', 'Romanian'),
    ('russian', 'Russian'),
    ('serbian', 'Serbian'),
    ('slovak', 'Slovak'),
    ('slovenian', 'Slovenian'),
    ('spanish', 'Spanish'),
    ('swedish', 'Swedish'),
    ('thai', 'Thai'),
    ('turkish', 'Turkish'),
    ('ukrainian', 'Ukrainian'),
    ('vietnamese', 'Vietnamese'),
]

SUPPORTED_LANGUAGES_AND_DEFAULT = [ ('default', 'Default') ] + SUPPORTED_LANGUAGES
