# Generated by Django 4.2.1 on 2023-05-14 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLARAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('l2', models.CharField(max_length=100, verbose_name='L2 Language')),
                ('l1', models.CharField(max_length=100, verbose_name='L1 Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
