# Generated by Django 4.2.1 on 2023-05-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0003_claraproject_internal_id_alter_claraproject_l1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claraproject',
            name='l1',
            field=models.CharField(choices=[('arabic', 'Arabic'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('english', 'English'), ('faroese', 'Faroese'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('icelandic', 'Icelandic'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('latin', 'Latin'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese')], max_length=50),
        ),
        migrations.AlterField(
            model_name='claraproject',
            name='l2',
            field=models.CharField(choices=[('arabic', 'Arabic'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('english', 'English'), ('faroese', 'Faroese'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('icelandic', 'Icelandic'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('latin', 'Latin'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese')], max_length=50),
        ),
    ]
