# Generated by Django 4.2.1 on 2023-05-16 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0004_alter_claraproject_l1_alter_claraproject_l2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLARAProjectAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit')], max_length=10)),
                ('text_version', models.CharField(choices=[('plain', 'Plain'), ('segmented', 'Segmented'), ('gloss', 'Gloss'), ('lemma', 'Lemma')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.claraproject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
