# Generated by Django 4.2.1 on 2023-05-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0005_claraprojectaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='url',
            new_name='external_url',
        ),
    ]
