# Generated by Django 4.2.1 on 2023-05-26 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0006_auto_20230526_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clara_app.claraproject'),
        ),
        migrations.AlterField(
            model_name='content',
            name='external_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
