# Generated by Django 4.2.1 on 2023-06-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0011_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
