# Generated by Django 4.2.1 on 2023-07-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0017_alter_apicall_user_alter_claraproject_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
