# Generated by Django 4.2.1 on 2023-10-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0021_humanaudioinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanaudioinfo',
            name='manual_align_metadata_file',
            field=models.FileField(blank=True, null=True, upload_to='metadata_files/'),
        ),
        migrations.AlterField(
            model_name='humanaudioinfo',
            name='voice_talent_id',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
