# Generated by Django 4.2.1 on 2023-11-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0026_alter_claraproject_l1_alter_claraproject_l2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('phonetic', 'Phonetic')], default='normal', max_length=10),
        ),
    ]
