# Generated by Django 4.2.1 on 2023-11-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0027_content_text_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneticHumanAudioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_for_segments', models.BooleanField(default=False)),
                ('use_for_words', models.BooleanField(default=False)),
                ('voice_talent_id', models.CharField(default='anonymous', max_length=200)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phonetic_human_audio_info', to='clara_app.claraproject')),
            ],
        ),
    ]
