# Generated by Django 4.2.1 on 2023-12-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0030_phonetichumanaudioinfo_use_for_segments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='task_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
