# Generated by Django 4.2.1 on 2024-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0031_taskupdate_read_taskupdate_task_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagemaster',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
