# Generated by Django 4.2.1 on 2024-01-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0035_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif')], max_length=50)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=50)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='format_preferences', to='clara_app.claraproject')),
            ],
        ),
    ]
