# Generated by Django 4.2.1 on 2024-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0036_formatpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatpreferences',
            name='concordance_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='formatpreferences',
            name='concordance_font_type',
            field=models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif')], default='serif', max_length=50),
        ),
        migrations.AddField(
            model_name='formatpreferences',
            name='concordance_text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=50),
        ),
        migrations.AlterField(
            model_name='formatpreferences',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='formatpreferences',
            name='font_type',
            field=models.CharField(choices=[('sans-serif', 'Sans Serif'), ('serif', 'Serif')], default='serif', max_length=50),
        ),
        migrations.AlterField(
            model_name='formatpreferences',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=50),
        ),
    ]
