# Generated by Django 4.2.1 on 2024-01-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0037_formatpreferences_concordance_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatpreferences',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('huge', 'Huge'), ('HUGE', 'HUGE')], default='medium', max_length=50),
        ),
    ]
