# Generated by Django 4.2.1 on 2024-01-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0039_humanaudioinfo_preferred_tts_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetichumanaudioinfo',
            name='preferred_tts_engine',
            field=models.CharField(choices=[('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='phonetichumanaudioinfo',
            name='preferred_tts_voice',
            field=models.CharField(choices=[('none', 'None')], default='none', max_length=20),
        ),
    ]
