# Generated by Django 4.2.1 on 2024-01-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0041_alter_humanaudioinfo_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfiguration',
            name='clara_version',
            field=models.CharField(choices=[('simple_clara', 'Simple C-LARA'), ('full_clara', 'Full C-LARA')], default='full_clara', max_length=20),
        ),
    ]
