# Generated by Django 4.2.1 on 2024-01-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0042_userconfiguration_clara_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfiguration',
            name='gpt_model',
            field=models.CharField(default='gpt-4-1106-preview', max_length=50),
        ),
        migrations.AlterField(
            model_name='userconfiguration',
            name='max_annotation_words',
            field=models.IntegerField(default=250),
        ),
    ]
