# Generated by Django 4.2.1 on 2024-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0048_readinghistory_internal_id_readinghistory_l2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claraproject',
            name='l1',
            field=models.CharField(choices=[('american english', 'American English'), ('arabic', 'Arabic'), ('australian english', 'Australian English'), ('barngarla', 'Barngarla'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('cantonese', 'Cantonese'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('drehu', 'Drehu'), ('dutch', 'Dutch'), ('english', 'English'), ('faroese', 'Faroese'), ('farsi', 'Farsi'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('iaai', 'Iaai'), ('icelandic', 'Icelandic'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('latin', 'Latin'), ('malay', 'Malay'), ('mandarin', 'Mandarin'), ('māori', 'Māori'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese')], max_length=50),
        ),
        migrations.AlterField(
            model_name='claraproject',
            name='l2',
            field=models.CharField(choices=[('american english', 'American English'), ('arabic', 'Arabic'), ('australian english', 'Australian English'), ('barngarla', 'Barngarla'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('cantonese', 'Cantonese'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('drehu', 'Drehu'), ('dutch', 'Dutch'), ('english', 'English'), ('faroese', 'Faroese'), ('farsi', 'Farsi'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('iaai', 'Iaai'), ('icelandic', 'Icelandic'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('latin', 'Latin'), ('malay', 'Malay'), ('mandarin', 'Mandarin'), ('māori', 'Māori'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese')], max_length=50),
        ),
        migrations.AlterField(
            model_name='languagemaster',
            name='language',
            field=models.CharField(choices=[('default', 'Default'), ('american english', 'American English'), ('arabic', 'Arabic'), ('australian english', 'Australian English'), ('barngarla', 'Barngarla'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('cantonese', 'Cantonese'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('drehu', 'Drehu'), ('dutch', 'Dutch'), ('english', 'English'), ('faroese', 'Faroese'), ('farsi', 'Farsi'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('iaai', 'Iaai'), ('icelandic', 'Icelandic'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('latin', 'Latin'), ('malay', 'Malay'), ('mandarin', 'Mandarin'), ('māori', 'Māori'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese')], max_length=50),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='l2',
            field=models.CharField(choices=[('american english', 'American English'), ('arabic', 'Arabic'), ('australian english', 'Australian English'), ('barngarla', 'Barngarla'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('cantonese', 'Cantonese'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('drehu', 'Drehu'), ('dutch', 'Dutch'), ('english', 'English'), ('faroese', 'Faroese'), ('farsi', 'Farsi'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('iaai', 'Iaai'), ('icelandic', 'Icelandic'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('latin', 'Latin'), ('malay', 'Malay'), ('mandarin', 'Mandarin'), ('māori', 'Māori'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese')], max_length=50),
        ),
    ]
