# Generated by Django 4.2.1 on 2024-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0049_alter_claraproject_l1_alter_claraproject_l2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='require_phonetic_text',
            field=models.BooleanField(default=False),
        ),
    ]
