# Generated by Django 4.2.1 on 2024-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0052_alter_humanaudioinfo_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanaudioinfo',
            name='use_context',
            field=models.BooleanField(default=False),
        ),
    ]
