# Generated by Django 4.2.1 on 2024-03-01 03:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0054_satisfactionquestionnaire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='satisfactionquestionnaire',
            unique_together={('user', 'project')},
        ),
    ]
