# Generated by Django 4.2.1 on 2024-03-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0055_alter_satisfactionquestionnaire_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='satisfactionquestionnaire',
            unique_together=set(),
        ),
    ]
