# Generated by Django 4.2.1 on 2024-03-03 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0057_alter_satisfactionquestionnaire_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='design_improvement',
            field=models.TextField(blank=True, verbose_name="What do you think the most important thing is to improve C-LARA's design?"),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='functionality_improvement',
            field=models.TextField(blank=True, verbose_name="What do you think the most important thing is to improve C-LARA's functionality?"),
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('american english', 'American English'), ('arabic', 'Arabic'), ('australian english', 'Australian English'), ('barngarla', 'Barngarla'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('cantonese', 'Cantonese'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('drehu', 'Drehu'), ('dutch', 'Dutch'), ('english', 'English'), ('faroese', 'Faroese'), ('farsi', 'Farsi'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('iaai', 'Iaai'), ('icelandic', 'Icelandic'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('latin', 'Latin'), ('malay', 'Malay'), ('mandarin', 'Mandarin'), ('māori', 'Māori'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese'), ('other', 'Other')], max_length=50, verbose_name='In which language will you mostly be creating texts?')),
                ('other_language', models.CharField(max_length=50, verbose_name='Specify other language if necessary')),
                ('native_or_near_native', models.BooleanField(default=False, verbose_name='Are you a native/near-native speaker of this language?')),
                ('text_type', models.CharField(choices=[('short_stories', 'Short stories'), ('essays', 'Essays'), ('poems', 'Poems'), ('picturebooks', 'Picture books'), ('existing_texts', 'Annotating existing texts'), ('other', 'Other')], max_length=50, verbose_name='What kind of texts are you most interested in creating?')),
                ('purpose', models.CharField(choices=[('just_curious', 'Just curious'), ('improve_own_skills', 'Want to improve own language skills'), ('classroom', 'Use for language teaching'), ('other', 'Other')], max_length=50, verbose_name='Why are you interested in using C-LARA?')),
                ('other_purpose', models.TextField(blank=True, verbose_name='If you wish, describe in a couple of sentences what you are planning to do.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50, verbose_name='Current status of request')),
                ('credit_assigned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('decision_comment', models.TextField(blank=True, help_text='Feedback or reason for decision.', verbose_name='Comment on Decision')),
                ('decision_made_at', models.DateTimeField(blank=True, null=True, verbose_name='Decision Made At')),
                ('funder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_request_funder', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
