# Generated by Django 4.2.1 on 2024-03-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0058_alter_satisfactionquestionnaire_design_improvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_funding_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='other_language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Specify other language if necessary'),
        ),
    ]
