# Generated by Django 4.2.1 on 2024-03-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0059_userprofile_is_funding_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50, verbose_name='Current status of request'),
        ),
    ]
