# Generated by Django 4.2.1 on 2024-03-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0060_alter_fundingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfiguration',
            name='open_ai_api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='other_language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Specify the language if it was not listed in the menu'),
        ),
    ]
