# Generated by Django 4.2.1 on 2024-03-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0065_userprofile_is_questionnaire_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satisfactionquestionnaire',
            name='cultural_appropriateness',
        ),
        migrations.RemoveField(
            model_name='satisfactionquestionnaire',
            name='design_improvement',
        ),
        migrations.RemoveField(
            model_name='satisfactionquestionnaire',
            name='functionality_improvement',
        ),
        migrations.RemoveField(
            model_name='satisfactionquestionnaire',
            name='language_correctness',
        ),
        migrations.RemoveField(
            model_name='satisfactionquestionnaire',
            name='shared_text',
        ),
        migrations.RemoveField(
            model_name='satisfactionquestionnaire',
            name='text_correspondence',
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='clara_version',
            field=models.CharField(choices=[('simple_clara', 'Simple C-LARA'), ('advanced_clara', 'Advanced C-LARA')], max_length=20, null=True, verbose_name='Which version of C-LARA do your answers apply to?'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='content_appropriateness',
            field=models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral or not applicable'), (4, 'Agree'), (5, 'Strongly agree')], null=True, verbose_name='The overall content was appropriate'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='correction_time_annotations',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('did_not_correct', "Didn't correct"), ('1_2_mins', '1-2 mins'), ('3_5_mins', '3-5 mins'), ('6_10_mins', '6-10 mins'), ('11_20_mins', '11-20 mins'), ('more_than_20_mins', 'More than 20 mins')], max_length=20, null=True, verbose_name='Time I spent correcting the annotations (segmentation/glosses/lemmas)'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='correction_time_text',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('did_not_correct', "Didn't correct"), ('1_2_mins', '1-2 mins'), ('3_5_mins', '3-5 mins'), ('6_10_mins', '6-10 mins'), ('11_20_mins', '11-20 mins'), ('more_than_20_mins', 'More than 20 mins')], max_length=30, null=True, verbose_name='Time I spent correcting the text:'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='cultural_elements',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral or not applicable'), (4, 'Agree'), (5, 'Strongly agree')], null=True, verbose_name='The text included appropriate elements of local culture'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='functionality_suggestion',
            field=models.TextField(blank=True, verbose_name='What other functionality would you like to add to C-LARA?'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='grammar_correctness',
            field=models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral or not applicable'), (4, 'Agree'), (5, 'Strongly agree')], null=True, verbose_name='The grammar in the text was correct'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='image_editing_time',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('did_not_correct', "Didn't correct"), ('1_5_mins', '1-5 mins'), ('6_15_mins', '6-15 mins'), ('15_mins_hour', '15 mins to an hour'), ('more_than_an_hour', 'More than an hour')], max_length=30, null=True, verbose_name='Time spent regenerating/editing the image(s)'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='purpose_text',
            field=models.TextField(blank=True, verbose_name='Tell us about the purpose of the text you created (e.g. educational material, professional report, creative writing, articles for public use, technical documentation, personal use, social media content, research and analysis, entertainment, etc.)'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='shared_intent',
            field=models.CharField(choices=[('have_shared', 'Have shared'), ('will_certainly_share', 'Will certainly share'), ('may_share', 'May share'), ('wont_share', "Won't share")], max_length=30, null=True, verbose_name='I have shared/intend to share this text with other people'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='style_appropriateness',
            field=models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral or not applicable'), (4, 'Agree'), (5, 'Strongly agree')], null=True, verbose_name='The style was appropriate'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='text_type',
            field=models.CharField(choices=[('story', 'Story'), ('essay', 'Essay'), ('poem', 'Poem'), ('play', 'Play'), ('newspaper_article', 'Newspaper Article'), ('annotated_existing_text', 'Annotating Existing Text'), ('other', 'Other')], max_length=30, null=True, verbose_name='What type of text did you produce?'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='ui_improvement_suggestion',
            field=models.TextField(blank=True, verbose_name='How would you suggest we could improve the user interface design in C-LARA?'),
        ),
        migrations.AddField(
            model_name='satisfactionquestionnaire',
            name='vocabulary_appropriateness',
            field=models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral or not applicable'), (4, 'Agree'), (5, 'Strongly agree')], null=True, verbose_name='The vocabulary/choice of words was appropriate'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='image_match',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral or not applicable'), (4, 'Agree'), (5, 'Strongly agree')], null=True, verbose_name='The image(s) matched the content of the text'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='text_engagement',
            field=models.IntegerField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral or not applicable'), (4, 'Agree'), (5, 'Strongly agree')], null=True, verbose_name='I found the text engaging (funny/cute/moving/etc)'),
        ),
    ]
