# Generated by Django 4.2.1 on 2024-03-25 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0067_satisfactionquestionnaire_generated_by_ai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('human_ai_interaction', 'Analysis of human/AI collaboration'), ('annotation', 'Annotation of texts by AI'), ('classroom', 'Classroom experiments'), ('multimodal_formatting', 'Formatting/behaviour of multimodal texts'), ('languages_covered_by_ai', 'Languages covered by AI'), ('languages_not_covered_by_ai', 'Languages not covered by AI'), ('legacy_content', 'Legacy content'), ('legacy_software', 'Legacy software'), ('phonetic_texts', 'Phonetic texts'), ('simple_clara', 'Simple C-LARA'), ('social_network', 'Social network'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='content_appropriateness',
            field=models.IntegerField(choices=[(0, 'NOT APPLICABLE'), (5, 'Strongly agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly disagree')], null=True, verbose_name='The overall content was appropriate'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='correction_time_annotations',
            field=models.CharField(choices=[('NOT APPLICABLE', 'Not applicable'), ('did_not_correct', "Didn't correct"), ('1_2_mins', '1-2 mins'), ('3_5_mins', '3-5 mins'), ('6_10_mins', '6-10 mins'), ('11_20_mins', '11-20 mins'), ('more_than_20_mins', 'More than 20 mins')], max_length=20, null=True, verbose_name='Time I spent correcting the annotations (segmentation/glosses/lemmas)'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='correction_time_text',
            field=models.CharField(choices=[('NOT APPLICABLE', 'Not applicable'), ('did_not_correct', "Didn't correct"), ('1_2_mins', '1-2 mins'), ('3_5_mins', '3-5 mins'), ('6_10_mins', '6-10 mins'), ('11_20_mins', '11-20 mins'), ('more_than_20_mins', 'More than 20 mins')], max_length=30, null=True, verbose_name='Time I spent correcting the text:'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='cultural_elements',
            field=models.IntegerField(choices=[(0, 'NOT APPLICABLE'), (5, 'Strongly agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly disagree')], null=True, verbose_name='The text included appropriate elements of local culture'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='generated_by_ai',
            field=models.BooleanField(choices=[(True, 'Generated by C-LARA/another AI'), (False, 'Written by a human')], null=True, verbose_name='Was your text generated by C-LARA/another AI, or was it written by a human?'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='grammar_correctness',
            field=models.IntegerField(choices=[(0, 'NOT APPLICABLE'), (5, 'Strongly agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly disagree')], null=True, verbose_name='The grammar in the text was correct'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='image_editing_time',
            field=models.CharField(choices=[('NOT APPLICABLE', 'Not applicable'), ('did_not_correct', "Didn't correct"), ('1_5_mins', '1-5 mins'), ('6_15_mins', '6-15 mins'), ('15_mins_hour', '15 mins to an hour'), ('more_than_an_hour', 'More than an hour')], max_length=30, null=True, verbose_name='Time spent regenerating/editing the image(s)'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='image_match',
            field=models.IntegerField(choices=[(0, 'NOT APPLICABLE'), (5, 'Strongly agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly disagree')], null=True, verbose_name='The image(s) matched the content of the text'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='style_appropriateness',
            field=models.IntegerField(choices=[(0, 'NOT APPLICABLE'), (5, 'Strongly agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly disagree')], null=True, verbose_name='The style was appropriate'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='text_engagement',
            field=models.IntegerField(choices=[(0, 'NOT APPLICABLE'), (5, 'Strongly agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly disagree')], null=True, verbose_name='I found the text engaging (funny/cute/moving/etc)'),
        ),
        migrations.AlterField(
            model_name='satisfactionquestionnaire',
            name='vocabulary_appropriateness',
            field=models.IntegerField(choices=[(0, 'NOT APPLICABLE'), (5, 'Strongly agree'), (4, 'Agree'), (3, 'Neutral'), (2, 'Disagree'), (1, 'Strongly disagree')], null=True, verbose_name='The vocabulary/choice of words was appropriate'),
        ),
        migrations.CreateModel(
            name='AudioMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.CharField(max_length=255)),
                ('language_id', models.CharField(max_length=255)),
                ('voice_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('context', models.TextField(default='')),
                ('file_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audio Metadata',
                'verbose_name_plural': 'Audio Metadata',
                'indexes': [models.Index(fields=['engine_id', 'language_id', 'voice_id', 'text', 'context'], name='audio_meta_composite_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wants_email', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clara_app.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='registered_users',
            field=models.ManyToManyField(related_name='registered_activities', through='clara_app.ActivityRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(default=0)),
                ('week', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity', 'week')},
            },
        ),
    ]
