# Generated by Django 4.2.1 on 2024-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0071_alter_claraproject_l1_alter_claraproject_l2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('associated_text', models.TextField(blank=True, default='')),
                ('associated_areas', models.TextField(blank=True, default='')),
                ('page', models.IntegerField(default=1)),
                ('position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('inline', 'Inline')], default='top', max_length=10)),
            ],
            options={
                'verbose_name': 'Image Metadata',
                'verbose_name_plural': 'Image Metadata',
            },
        ),
        migrations.AddConstraint(
            model_name='imagemetadata',
            constraint=models.UniqueConstraint(fields=('project_id', 'image_name'), name='unique_project_image'),
        ),
    ]
