# Generated by Django 4.2.1 on 2024-04-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0072_phoneticencoding_alter_claraproject_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='resolution',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('solved', 'Solved'), ('wont_do', "Won't Do")], default='unresolved', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='posted', max_length=20),
        ),
    ]
