# Generated by Django 4.2.1 on 2024-04-11 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0073_activity_resolution_activity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentActivityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(choices=[(0, 'No vote'), (1, 'Most important'), (2, 'Second most important'), (3, 'Third most important')])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
