# Generated by Django 4.2.1 on 2024-04-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0074_currentactivityvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('human_ai_interaction', 'Analysis of human/AI collaboration'), ('annotation', 'Annotation of texts by AI'), ('classroom', 'Classroom experiments'), ('creating_texts', 'Creation of texts by AI'), ('multimodal_formatting', 'Formatting/behaviour of multimodal texts'), ('languages_covered_by_ai', 'Languages covered by AI'), ('languages_not_covered_by_ai', 'Languages not covered by AI'), ('legacy_content', 'Legacy content'), ('legacy_software', 'Legacy software'), ('new_functionality', 'New C-LARA functionality not in other categories'), ('phonetic_texts', 'Phonetic texts'), ('publications_and_conferences', 'Publications, conferences and workshops'), ('refactoring', 'Refactoring software'), ('simple_clara', 'Simple C-LARA'), ('social_network', 'Social network'), ('other', 'Other')], max_length=50),
        ),
    ]
