# Generated by Django 4.2.1 on 2024-04-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0075_remove_imagemetadata_unique_project_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audiometadata',
            unique_together=set(),
        ),
    ]
