# Generated by Django 4.2.1 on 2024-04-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0076_alter_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanaudioinfo',
            name='preferred_tts_voice',
            field=models.CharField(choices=[('none', 'None'), ('alloy', 'Alloy (OpenAI)'), ('echo', 'Echo (OpenAI)'), ('fable', 'Fable (OpenAI)'), ('onyx', 'Onyx (OpenAI)'), ('nova', 'Nova (OpenAI)'), ('shimmer', 'Shimmer (OpenAI)'), ('ga_UL_anb_nemo', 'ga_UL_anb_nemo (ABAIR)'), ('ga_UL_anb_exthts', 'ga_UL_anb_exthts (ABAIR)'), ('ga_UL_anb_piper', 'ga_UL_anb_piper (ABAIR)'), ('ga_CO_snc_nemo', 'ga_CO_snc_nemo (ABAIR)'), ('ga_CO_snc_exthts', 'ga_CO_snc_exthts (ABAIR)'), ('ga_CO_snc_piper', 'ga_CO_snc_piper (ABAIR)'), ('ga_CO_pmc_exthts', 'ga_CO_pmc_exthts (ABAIR)'), ('ga_CO_pmc_nemo', 'ga_CO_pmc_nemo (ABAIR)'), ('ga_MU_nnc_nemo', 'ga_MU_nnc_nemo (ABAIR)'), ('ga_MU_nnc_exthts', 'ga_MU_nnc_exthts (ABAIR)'), ('ga_MU_dms_nemo', 'ga_MU_dms_nemo (ABAIR)'), ('ga_MU_dms_piper', 'ga_MU_dms_piper (ABAIR)')], default='none', max_length=20),
        ),
    ]
