# Generated by Django 4.2.1 on 2024-04-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0076_alter_audiometadata_unique_together'),
    ]

##    operations = [
##        migrations.RenameIndex(
##            model_name='phoneticlexiconhistory',
##            new_name='idx_word_history1',
##            old_name='idx_word_history',
##        ),
##    ]
