# Generated by Django 4.2.1 on 2024-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0077_alter_humanaudioinfo_preferred_tts_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanaudioinfo',
            name='preferred_tts_engine',
            field=models.CharField(choices=[('none', 'None'), ('google', 'Google TTS'), ('openai', 'OpenAI TTS'), ('eleven_labs', 'Eleven Labs TTS'), ('abair', 'ABAIR')], default='none', max_length=20),
        ),
    ]
