# Generated by Django 4.2.1 on 2024-04-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0077_rename_idx_word_history_idx_word_history1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneticLexiconHistory',
        ),
    ]
