# Generated by Django 4.2.1 on 2024-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0081_imagemetadata_content_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='description_variable',
            field=models.CharField(blank=True, default='', help_text='Variable name for storing image understanding result.', max_length=255),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='request_type',
            field=models.CharField(choices=[('image-generation', 'Generation'), ('image-understanding', 'Understanding')], default='image-generatio', max_length=20),
        ),
    ]
