# Generated by Django 4.2.1 on 2024-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0084_imagedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='description_variables',
            field=models.JSONField(blank=True, default=list, help_text='List of description variables for this image generation request.'),
        ),
    ]
