# Generated by Django 4.2.1 on 2024-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0085_imagemetadata_description_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='claraproject',
            name='use_translation_for_images',
            field=models.BooleanField(default=False, help_text='Use translations for generating coherent image sets.'),
        ),
    ]
