# Generated by Django 4.2.1 on 2024-08-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0086_claraproject_use_translation_for_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='unique_access_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='clara_app.content')),
            ],
            options={
                'unique_together': {('content', 'ip_address')},
            },
        ),
    ]
