# Generated by Django 4.2.1 on 2024-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0087_content_unique_access_count_contentaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('associated_text', models.TextField(blank=True)),
                ('associated_areas', models.TextField(blank=True)),
                ('page', models.IntegerField(default=1)),
                ('position', models.CharField(default='bottom', max_length=200)),
                ('style_description', models.TextField(blank=True)),
                ('content_description', models.TextField(blank=True)),
                ('user_prompt', models.TextField(blank=True)),
                ('request_type', models.CharField(default='image-generation', max_length=200)),
                ('description_variable', models.CharField(blank=True, max_length=200)),
                ('description_variables', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
