# Generated by Django 4.2.1 on 2024-11-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0090_claraproject_uses_coherent_image_set_v2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedimagemetadata',
            name='advice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='archivedimagemetadata',
            name='image_type',
            field=models.CharField(default='page', max_length=20),
        ),
    ]
