# Generated by Django 4.2.1 on 2024-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0091_archivedimagemetadata_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='element_name',
            field=models.CharField(blank=True, default='', help_text='Name of element for an element entry.', max_length=255),
        ),
    ]
