# Generated by Django 4.2.1 on 2024-11-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0092_imagemetadata_element_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedimagemetadata',
            name='element_name',
            field=models.CharField(blank=True, default='', help_text='Name of element for an element entry.', max_length=255),
        ),
    ]
