# Generated by Django 4.2.1 on 2025-02-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0094_community_communitymembership_claraproject_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('human_ai_interaction', 'Analysis of human/AI collaboration'), ('annotation', 'Annotation of texts by AI'), ('classroom', 'Classroom experiments'), ('creating_images', 'Creating images'), ('creating_texts', 'Creation of texts by AI'), ('design', 'Design issues for C-LARA platform'), ('multimodal_formatting', 'Formatting/behaviour of multimodal texts'), ('languages_covered_by_ai', 'Languages covered by AI'), ('languages_not_covered_by_ai', 'Languages not covered by AI'), ('legacy_content', 'Legacy content'), ('legacy_software', 'Legacy software'), ('mwes', 'Multi-Word Expressions'), ('new_functionality', 'New C-LARA functionality not in other categories'), ('phonetic_texts', 'Phonetic texts'), ('publications_and_conferences', 'Publications, conferences and workshops'), ('refactoring', 'Refactoring software'), ('simple_clara', 'Simple C-LARA'), ('social_network', 'Social network'), ('ukrainian', 'Ukrainian learners'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='claraproject',
            name='simple_clara_type',
            field=models.CharField(choices=[('create_text_and_image', 'Use the AI to create text and a single image based on your instructions'), ('create_text_and_multiple_images', 'Use the AI to create text and an image for each page based on your instructions'), ('create_text_from_image', 'Upload an image and use the AI to create text from it'), ('annotate_existing_text', 'Paste in your own text and use the AI to convert it to multimodal form')], default='create_text_and_image', max_length=50),
        ),
    ]
