# Generated by Django 4.2.1 on 2025-06-13 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0096_claraproject_has_image_questionnaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TQBookLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.content')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.textquestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='TQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('book_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.tqbooklink')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.textquestionnaire')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('order', models.PositiveSmallIntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.textquestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='TQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likert', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.tqquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.tqresponse')),
            ],
        ),
    ]
