# Generated by Django 4.2.1 on 2025-07-12 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clara_app', '0097_textquestionnaire_tqbooklink_tqresponse_tqquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalisationBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('src', models.TextField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.localisationbundle')),
            ],
            options={
                'unique_together': {('bundle', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BundleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('default', 'Default'), ('american english', 'American English'), ('ancient egyptian', 'Ancient Egyptian'), ('arabic', 'Arabic'), ('australian english', 'Australian English'), ('barngarla', 'Barngarla'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('cantonese', 'Cantonese'), ('chinese', 'Chinese'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('drehu', 'Drehu'), ('dutch', 'Dutch'), ('english', 'English'), ('esperanto', 'Esperanto'), ('estonian', 'Estonian'), ('faroese', 'Faroese'), ('farsi', 'Farsi'), ('finnish', 'Finnish'), ('french', 'French'), ('german', 'German'), ('greek', 'Greek'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('iaai', 'Iaai'), ('icelandic', 'Icelandic'), ('indonesian', 'Indonesian'), ('irish', 'Irish'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('kok kaper', 'Kok Kaper'), ('korean', 'Korean'), ('kunjen', 'Kunjen'), ('latin', 'Latin'), ('malay', 'Malay'), ('mandarin', 'Mandarin'), ('māori', 'Māori'), ('norwegian', 'Norwegian'), ('old norse', 'Old Norse'), ('paicî', 'Paicî'), ('pitjantjatjara', 'Pitjantjatjara'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('spanish', 'Spanish'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('turkish', 'Turkish'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese'), ('welsh', 'Welsh'), ('west greenlandic', 'West Greenlandic'), ('yirr yorront', 'Yirr Yorront')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clara_app.bundleitem')),
            ],
            options={
                'unique_together': {('item', 'lang')},
            },
        ),
    ]
