# Generated by Django 4.2.1 on 2025-08-23 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0098_localisationbundle_bundleitem_bundletranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestionnaire',
            name='per_page_questions',
            field=models.TextField(blank=True, help_text='Optional. One question per line. If present, tq_fill will run a page-by-page step.'),
        ),
        migrations.AddField(
            model_name='tqanswer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='tqanswer',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
