# Generated by Django 4.2.1 on 2025-08-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0099_textquestionnaire_per_page_questions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tqquestion',
            options={'ordering': ['scope', 'order']},
        ),
        migrations.AddField(
            model_name='tqquestion',
            name='scope',
            field=models.CharField(choices=[('BOOK', 'Book-level'), ('PAGE', 'Per-page')], default='BOOK', max_length=8),
        ),
        migrations.AlterField(
            model_name='tqquestion',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tqquestion',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='tqquestion',
            unique_together={('questionnaire', 'scope', 'order')},
        ),
    ]
