# Generated by Django 4.2.1 on 2025-08-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clara_app', '0100_alter_tqquestion_options_tqquestion_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tqresponse',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='tqresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('submitted_at__isnull', True)), fields=('questionnaire', 'book_link', 'rater'), name='uniq_open_tqresponse'),
        ),
    ]
